---
- name: Copy the content to webserver
  become: yes
  hosts: all
  tasks:
    - name: copy the Blue content to server
      file:
        path: /var/www/html
        state: directory
    - name: test
      copy:
        content: Welcome to Myserver, i am Blue
        dest: /var/www/html/index.html

    - name: copy the Green content to server    
      copy:
        content: Welcome to Myserver, i am Green
        dest: /var/www/html/index.html
