---
- name: This is a hello-world example
  hosts: all
  become: yes
  tasks:
    - name: Create a file called '/tmp/testfile.txt' with the content 'hello world'.
      yum:
        name: httpd
        state: latest
    - name: install
      service:
         name: httpd
         state: enabled
