---
- name: This is a hello-world example
  hosts: prodhost
  tasks:
    - name: Create a file called '/tmp/testfile.txt' with the content 'hello world'.
      yum:
        name: httpd
        state: latest
      service:
         name: httpd
         state: enabled
