---
- name: This is a hello-world example
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Create a file called
      yum:
        name: httpd
        state: latest
    - name: install
      service:
         name: httpd
         state: restarted
